name = "lean-floats"
version = "0.1.0"
defaultTargets = ["LeanFloats"]

[[lean_lib]]
name = "LeanFloats"

[[require]]
name = "mathlib4"
git = "https://github.com/leanprover-community/mathlib4-nightly-testing"
rev = "281cecb69a97a85be7a3ddf468c4682bd54e65fa"
