name = "lean-floats"
version = "0.1.0"
defaultTargets = ["LeanFloats"]

[[lean_lib]]
name = "LeanFloats"

[[require]]
name = "mathlib4"
git = "https://github.com/leanprover-community/mathlib4-nightly-testing"
rev = "74eb5f141a2ca78e770ecfce90187c52f5178355"
